### ISSUE TITLE
LICENCE ?

### ISSUE THREAD

**Issue by cquest** [sigrennesmetropole/mapillary_rm#5]
Pourriez-vous ajouter un fichier LICENSE.txt pour définir la licence du contenu de ce projet ?

Merci d'avance

**Comment by PanierAvide** [comment]
Sur les scripts que j'ai écrit, le code est en GPL 3. @MaelREBOUX ça te va si je fais une modif pour passer tout le dépôt en GPL 3 y compris ce que tu as écrit ?

**Comment by MaelREBOUX** [comment]
Fait avec https://github.com/sigrennesmetropole/mapillary_rm/commit/500ad71cccaac9d27fa079eb2af2d5b9e149c525
